@echo off
call mkbcc32 demoAddr
call mkbcc32 demoDate
call mkbcc32 demoDir
call mkbcc32 demoDirEntry
call mkbcc32 demoEnv
call mkbcc32 demoFile-FileName
call mkbcc32 demoFileRd-FileWr
call mkbcc32 demoFmt
call mkbcc32 demoLongRLib
call mkbcc32 demoMem
call mkbcc32 demoRd-Wr
call mkbcc32 demoRLib
call mkbcc32 demoScan
call mkbcc32 demoShortMem
call mkbcc32 demoString
call mkbcc32 demoTime
